### PR TITLE
add localcache

### PR DESCRIPTION
**Pull request by Flash-LHR**

### CODE REVIEW

**Comment by liuzengh** [comment]
Please add  a localcache.yml  in here: https://github.com/trpc-ecosystem/go-database/tree/main/.github/workflows, you can refer to other documents in the link.

**Comment by Flash-LHR** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by liuzengh — APPROVED** [review]
LGTM

**Comment by Flash-LHR** [comment]
request merge

**Pull request merged**
